# Generated by Django 2.2.3 on 2019-08-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_O',
            fields=[
                ('Province', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
