# Generated by Django 2.2.3 on 2019-08-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_d_o'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_O1',
            fields=[
                ('Year', models.IntegerField()),
                ('Province', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Data', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='D_O',
        ),
    ]
