# Generated by Django 2.2.3 on 2019-08-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190801_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_O2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Province', models.CharField(max_length=15)),
                ('Data', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='D_O1',
        ),
    ]
